CREATE TABLE `syseng_decoupling_prod.netsuite_fin_transactions_header` (
  id STRING OPTIONS (description = "Netsuite internal id. Internal id - generated by Netsuite"),
  record_type STRING OPTIONS (description = "Type of record (e.g., 'invoice'). Parked for future use"),
  doc_number STRING OPTIONS (description = "Unique transaction reference (e.g., 'INV23098965'). Can be applied for invoice, payments and credit memos"),
  transaction_number STRING OPTIONS (description = "Unique NS internal transaction reference (e.g., 'CUSTINVC153694'). Populated in case of record deletion"),
  status STRING OPTIONS (description = "Payment status (e.g., 'Paid In Full')"),
  document_date DATE OPTIONS (description = "Document creation date (format: MM/DD/YYYY)"),
  due_date DATE OPTIONS (description = "Payment due date (format: MM/DD/YYYY)"),
  amount_net_of_tax NUMERIC OPTIONS (description = "Net amount before tax"),
  amount_transaction_tax_total NUMERIC OPTIONS (description = "Tax total amount"),
  amount_transaction_total NUMERIC OPTIONS (description = "Total amount at header level including tax"),
  customer_fivetran_account_id STRING OPTIONS (description = "Internal Fivetran id of fivetran customer"),
  reseller_marketplace_fivetran_account_id STRING OPTIONS (description = "Internal Fivetran id of Reseller or Marketplace"),
  last_modified_date DATETIME OPTIONS (description = "Last modified date (format: MM/DD/YYYY HH:MM am/pm)"),
  currency STRING OPTIONS (description = "Transaction currency (e.g., 'US Dollar'; consider ISO codes like USD). Parked for future use"),
  amt_remaining_trxn_currency NUMERIC OPTIONS (description = "Outstanding balance in transaction currency (e.g., 0.00 if paid)"),
  amt_paid_trxn_currency NUMERIC OPTIONS (description = "Amount paid in transaction currency (e.g., 49059.87)"),
  created_at DATETIME OPTIONS (description = "Record creation timestamp")
)
OPTIONS (
  description = "Table storing Netsuite transaction records at header level."
);
